// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/dataprofile.proto

package Profiles;

public final class Dataprofile {
  private Dataprofile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Profiles.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double cpu = 1;</code>
     * @return Whether the cpu field is set.
     */
    boolean hasCpu();
    /**
     * <code>required double cpu = 1;</code>
     * @return The cpu.
     */
    double getCpu();

    /**
     * <code>required double networkIn = 2;</code>
     * @return Whether the networkIn field is set.
     */
    boolean hasNetworkIn();
    /**
     * <code>required double networkIn = 2;</code>
     * @return The networkIn.
     */
    double getNetworkIn();

    /**
     * <code>required double networkOut = 3;</code>
     * @return Whether the networkOut field is set.
     */
    boolean hasNetworkOut();
    /**
     * <code>required double networkOut = 3;</code>
     * @return The networkOut.
     */
    double getNetworkOut();

    /**
     * <code>required double memory = 4;</code>
     * @return Whether the memory field is set.
     */
    boolean hasMemory();
    /**
     * <code>required double memory = 4;</code>
     * @return The memory.
     */
    double getMemory();
  }
  /**
   * Protobuf type {@code Profiles.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Profiles.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              cpu_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              networkIn_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              networkOut_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              memory_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Dataprofile.internal_static_Profiles_Data_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Dataprofile.internal_static_Profiles_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Data.class, Builder.class);
    }

    private int bitField0_;
    public static final int CPU_FIELD_NUMBER = 1;
    private double cpu_;
    /**
     * <code>required double cpu = 1;</code>
     * @return Whether the cpu field is set.
     */
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double cpu = 1;</code>
     * @return The cpu.
     */
    public double getCpu() {
      return cpu_;
    }

    public static final int NETWORKIN_FIELD_NUMBER = 2;
    private double networkIn_;
    /**
     * <code>required double networkIn = 2;</code>
     * @return Whether the networkIn field is set.
     */
    public boolean hasNetworkIn() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double networkIn = 2;</code>
     * @return The networkIn.
     */
    public double getNetworkIn() {
      return networkIn_;
    }

    public static final int NETWORKOUT_FIELD_NUMBER = 3;
    private double networkOut_;
    /**
     * <code>required double networkOut = 3;</code>
     * @return Whether the networkOut field is set.
     */
    public boolean hasNetworkOut() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double networkOut = 3;</code>
     * @return The networkOut.
     */
    public double getNetworkOut() {
      return networkOut_;
    }

    public static final int MEMORY_FIELD_NUMBER = 4;
    private double memory_;
    /**
     * <code>required double memory = 4;</code>
     * @return Whether the memory field is set.
     */
    public boolean hasMemory() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required double memory = 4;</code>
     * @return The memory.
     */
    public double getMemory() {
      return memory_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCpu()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNetworkIn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNetworkOut()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, cpu_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, networkIn_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, networkOut_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeDouble(4, memory_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, cpu_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, networkIn_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, networkOut_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, memory_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Data)) {
        return super.equals(obj);
      }
      Data other = (Data) obj;

      if (hasCpu() != other.hasCpu()) return false;
      if (hasCpu()) {
        if (Double.doubleToLongBits(getCpu())
            != Double.doubleToLongBits(
                other.getCpu())) return false;
      }
      if (hasNetworkIn() != other.hasNetworkIn()) return false;
      if (hasNetworkIn()) {
        if (Double.doubleToLongBits(getNetworkIn())
            != Double.doubleToLongBits(
                other.getNetworkIn())) return false;
      }
      if (hasNetworkOut() != other.hasNetworkOut()) return false;
      if (hasNetworkOut()) {
        if (Double.doubleToLongBits(getNetworkOut())
            != Double.doubleToLongBits(
                other.getNetworkOut())) return false;
      }
      if (hasMemory() != other.hasMemory()) return false;
      if (hasMemory()) {
        if (Double.doubleToLongBits(getMemory())
            != Double.doubleToLongBits(
                other.getMemory())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCpu()) {
        hash = (37 * hash) + CPU_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getCpu()));
      }
      if (hasNetworkIn()) {
        hash = (37 * hash) + NETWORKIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getNetworkIn()));
      }
      if (hasNetworkOut()) {
        hash = (37 * hash) + NETWORKOUT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getNetworkOut()));
      }
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            Double.doubleToLongBits(getMemory()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Profiles.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Profiles.Data)
        DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Dataprofile.internal_static_Profiles_Data_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Dataprofile.internal_static_Profiles_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Data.class, Builder.class);
      }

      // Construct using Profiles.Dataprofile.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        cpu_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        networkIn_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        networkOut_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        memory_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Dataprofile.internal_static_Profiles_Data_descriptor;
      }

      @Override
      public Data getDefaultInstanceForType() {
        return Data.getDefaultInstance();
      }

      @Override
      public Data build() {
        Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Data buildPartial() {
        Data result = new Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cpu_ = cpu_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.networkIn_ = networkIn_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.networkOut_ = networkOut_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.memory_ = memory_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Data) {
          return mergeFrom((Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Data other) {
        if (other == Data.getDefaultInstance()) return this;
        if (other.hasCpu()) {
          setCpu(other.getCpu());
        }
        if (other.hasNetworkIn()) {
          setNetworkIn(other.getNetworkIn());
        }
        if (other.hasNetworkOut()) {
          setNetworkOut(other.getNetworkOut());
        }
        if (other.hasMemory()) {
          setMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasCpu()) {
          return false;
        }
        if (!hasNetworkIn()) {
          return false;
        }
        if (!hasNetworkOut()) {
          return false;
        }
        if (!hasMemory()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double cpu_ ;
      /**
       * <code>required double cpu = 1;</code>
       * @return Whether the cpu field is set.
       */
      public boolean hasCpu() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double cpu = 1;</code>
       * @return The cpu.
       */
      public double getCpu() {
        return cpu_;
      }
      /**
       * <code>required double cpu = 1;</code>
       * @param value The cpu to set.
       * @return This builder for chaining.
       */
      public Builder setCpu(double value) {
        bitField0_ |= 0x00000001;
        cpu_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double cpu = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpu() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cpu_ = 0D;
        onChanged();
        return this;
      }

      private double networkIn_ ;
      /**
       * <code>required double networkIn = 2;</code>
       * @return Whether the networkIn field is set.
       */
      public boolean hasNetworkIn() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double networkIn = 2;</code>
       * @return The networkIn.
       */
      public double getNetworkIn() {
        return networkIn_;
      }
      /**
       * <code>required double networkIn = 2;</code>
       * @param value The networkIn to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkIn(double value) {
        bitField0_ |= 0x00000002;
        networkIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double networkIn = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetworkIn() {
        bitField0_ = (bitField0_ & ~0x00000002);
        networkIn_ = 0D;
        onChanged();
        return this;
      }

      private double networkOut_ ;
      /**
       * <code>required double networkOut = 3;</code>
       * @return Whether the networkOut field is set.
       */
      public boolean hasNetworkOut() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double networkOut = 3;</code>
       * @return The networkOut.
       */
      public double getNetworkOut() {
        return networkOut_;
      }
      /**
       * <code>required double networkOut = 3;</code>
       * @param value The networkOut to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkOut(double value) {
        bitField0_ |= 0x00000004;
        networkOut_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double networkOut = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetworkOut() {
        bitField0_ = (bitField0_ & ~0x00000004);
        networkOut_ = 0D;
        onChanged();
        return this;
      }

      private double memory_ ;
      /**
       * <code>required double memory = 4;</code>
       * @return Whether the memory field is set.
       */
      public boolean hasMemory() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required double memory = 4;</code>
       * @return The memory.
       */
      public double getMemory() {
        return memory_;
      }
      /**
       * <code>required double memory = 4;</code>
       * @param value The memory to set.
       * @return This builder for chaining.
       */
      public Builder setMemory(double value) {
        bitField0_ |= 0x00000008;
        memory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double memory = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        memory_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Profiles.Data)
    }

    // @@protoc_insertion_point(class_scope:Profiles.Data)
    private static final Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Data();
    }

    public static Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @Override
    public Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Profiles_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Profiles_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!google/protobuf/dataprofile.proto\022\010Pro" +
      "files\"J\n\004Data\022\013\n\003cpu\030\001 \002(\001\022\021\n\tnetworkIn\030" +
      "\002 \002(\001\022\022\n\nnetworkOut\030\003 \002(\001\022\016\n\006memory\030\004 \002(" +
      "\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Profiles_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Profiles_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Profiles_Data_descriptor,
        new String[] { "Cpu", "NetworkIn", "NetworkOut", "Memory", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
